apiVersion: v1
kind: Pod
metadata:
  name: calculator-svc
  labels:
    app: calculator 
spec:
  containers:
    - name: calculator
      imagePullPolicy: IfNotPresent
      image: cliffenator/calculator-app:latest